const fs = require('fs');

const htmlPath = 'index.html';
let html = fs.readFileSync(htmlPath, 'utf8');

const cardStart = html.indexOf('function card(p){');
const renderStart = html.indexOf('function render(){', cardStart);
const listenersStart = html.indexOf('["search","week","theme"]', renderStart);
if (cardStart < 0 || renderStart < 0 || listenersStart < 0) {
  throw new Error('Impossible de localiser le renderer du calendrier.');
}

const renderer = `function card(p){var ok=checked[p.id]?" checked":"";var option=p.choiceRequired?'<span class="option-label">'+esc(p.optionLabel||"Choix éditorial")+'</span>':"";return '<article class="post" data-t="'+esc(p.t)+'" data-option-group="'+esc(p.optionGroup||"")+'"><div class="post-head"><div class="meta"><span class="tag">'+esc(p.t)+'</span><span class="date">'+esc(p.date)+' · créneau à tester</span>'+option+'</div><h4>'+esc(p.title)+'</h4><p>'+esc(p.role)+'</p></div><div class="post-foot"><span class="tier">'+esc(p.tier)+' · '+esc(p.format)+'</span><label class="ready"><input class="readybox" data-id="'+esc(p.id)+'" type="checkbox"'+ok+'> prêt</label></div><details><summary>Ouvrir le brief complet</summary><div class="detail"><div class="detail-grid"><div class="box"><b>Objectif</b><span>'+esc(p.role)+'</span></div><div class="box"><b>CTA unique</b><span>'+esc(p.cta)+'</span></div><div class="box"><b>Direction visuelle</b><span>'+esc(p.visual)+'</span></div><div class="box"><b>Source / validation</b><span>'+esc(p.source)+'</span></div></div><div class="copy"><button class="copybtn" data-copy="'+encodeURIComponent(p.copy)+'" title="Copier l’angle bilingue">⧉</button>'+esc(p.copy)+'</div><div class="detail-grid"><div class="box"><b>Scénario de repli</b><span>'+esc(p.fallback)+'</span></div><div class="box"><b>KPI à regarder</b><span>'+esc(p.kpi)+'</span></div></div><div class="check"><div>'+esc(p.task)+'</div><div>Vérifier que la légende finale FR / EN reste sous 2 200 caractères au total.</div><div>Répondre aux premiers commentaires et corriger toute ambiguïté factuelle.</div></div></div></details></article>'}
function render(){var q=document.getElementById("search").value.toLocaleLowerCase("fr");var w=document.getElementById("week").value;var t=document.getElementById("theme").value;var list=posts.filter(function(p){return(w==="all"||String(p.w)===w)&&(t==="all"||p.t===t)&&(!q||Object.values(p).join(" ").toLocaleLowerCase("fr").includes(q))});var out="";[1,2,3,4].forEach(function(n){var a=list.filter(function(p){return p.w===n});if(!a.length)return;var days={};a.forEach(function(p){(days[p.date]||(days[p.date]=[])).push(p)});out+='<section class="week-group"><div class="week-title"><h3>'+meta[n][0]+'</h3><span>'+meta[n][1]+' · '+a.length+' cartes affichées</span></div>';Object.keys(days).forEach(function(day){var dayPosts=days[day];var hasChoice=dayPosts.some(function(p){return p.choiceRequired});out+='<div class="day-group"><div class="day-heading"><strong>'+esc(day)+'</strong>'+(hasChoice?'<span class="day-choice-note">Choisir une seule option</span>':"")+'</div><div class="posts">'+dayPosts.map(card).join("")+'</div></div>'});out+='</section>'});document.getElementById("posts").innerHTML=out||'<div class="panel"><h3>Aucun résultat</h3><p>Essayez un autre mot-clé ou réinitialisez les filtres.</p></div>';var main=posts.filter(function(p){return!p.isAlternative});var done=main.filter(function(p){return checked[p.id]}).length;document.getElementById("done").textContent=done;document.getElementById("shown").textContent=list.length+" carte"+(list.length>1?"s":"")+" affichée"+(list.length>1?"s":"");document.getElementById("bar").style.width=(main.length?done/main.length*100:0)+"%"}
`;
html = html.slice(0, cardStart) + renderer + html.slice(listenersStart);

const style = `\n    .day-group { margin: 0 0 22px; border: 1px solid rgba(18, 75, 98, .14); border-radius: 16px; overflow: hidden; background: rgba(255,255,255,.56); }\n    .day-heading { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 11px 15px; color: #123e52; background: #edf7f7; border-bottom: 1px solid rgba(18, 75, 98, .12); font-size: .88rem; }\n    .day-choice-note { color: #7a4d10; font-size: .76rem; font-weight: 700; letter-spacing: .02em; }\n    .option-label { display: inline-flex; align-items: center; padding: 4px 8px; border-radius: 999px; color: #6f4710; background: #fff3d8; font-size: .7rem; font-weight: 800; letter-spacing: .03em; }\n`;
html = html.replace('</style>', style + '  </style>');
fs.writeFileSync(htmlPath, html);
console.log('renderer patched: day groups, choice labels, 28-day progress');
