import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {parseHTML} from 'linkedom';
import {fixtureHTML,mockAPI} from './workspace-test-fixture.mjs';
import {mountWorkspace} from './workspace-v2.js';
import {installMediaValidationFixture} from './media-validation-test-fixture.mjs';
import {buildTaskProgressPresentation} from './task-progress-ui.js';
const source=await fs.readFile(new URL('./cockpit-ui.js',import.meta.url),'utf8');
const clientSource=await fs.readFile(new URL('./firebase-client.js',import.meta.url),'utf8');
const settle=()=>new Promise(resolve=>setTimeout(resolve,0));
assert.equal(buildTaskProgressPresentation({stage:'media_review'},{direction:{status:'selected',mediaIds:['photo']},agreement:{status:'pending'}}).media,false,'Le suivi des tâches ne confond pas choix DG et validation finale.');
for (const stage of ['media_in_progress','media_changes_requested']) assert.equal(buildTaskProgressPresentation({stage}).text,true,'Une correction média conserve le feu texte.');
for(const role of ['admin','director']) {
  const {document,window}=parseHTML(`<html><body>${fixtureHTML}</body></html>`);
  window.location={hash:'#/publications/test-first',search:'?interface=v2',href:'http://localhost/?interface=v2#/publications/test-first'};
  window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
  window.requestAnimationFrame=fn=>setTimeout(fn,0);window.cancelAnimationFrame=clearTimeout;
  globalThis.MutationObserver=window.MutationObserver;
  globalThis.CustomEvent=window.CustomEvent;
  globalThis.document=document;globalThis.window=window;
  const h=installMediaValidationFixture({document,window,source,clientSource,role});
  const api=mockAPI(document,window,role);api.getWorkflow=id=>h.state.workflows.get(id);api.getMedia=()=>[...h.state.mediaByEvent.values()].flat();api.getMediaDecision=id=>h.state.mediaDecisions.get(id);
  const workspace=mountWorkspace(api);
  const button=selector=>h.card.querySelector(selector);
  assert.equal(button('[data-gate="media"]').disabled,false,'Le feu visuel est actionnable en V2.');
  const panel=button('[data-media-validation-panel]');panel.open=false;
  button('[data-gate="media"]').click();assert.equal(panel.open,true);
  assert.equal(button('[data-gate="publication"]').disabled,true);
  button('[data-media-validation-force-open]').click();
  assert(!button('[data-media-validation-force]').hasAttribute('hidden'));
  button('[data-media-override]').click();await settle();assert.equal(h.writes.length,0,'Un motif vide ne déclenche aucune écriture.');
  button('[data-media-override-reason]').value='Aval confirmé pour cette photographie';
  h.rerender();assert.equal(button('[data-media-override-reason]').value,'Aval confirmé pour cette photographie');
  button('[data-media-validation-panel] [data-media-override]').click();await settle();
  assert.equal(h.state.workflows.get(h.eventId).stage,'final_approved',JSON.stringify(h.events));
  assert.equal(h.state.mediaDecisions.get(h.eventId).override.actorRole,role);
  if(role==='admin')assert.equal(h.state.mediaDecisions.get(h.eventId).direction.status,'none');
  assert.equal(h.archives.length,1);
  button('[data-media-validation-panel] [data-media-decision]').click();await settle();
  assert.equal(h.state.workflows.get(h.eventId).stage,'media_review');
  assert.equal(h.state.mediaDecisions.get(h.eventId).override.active,false);
  assert.equal(button('[data-gate="publication"]').disabled,true);
  assert.equal(h.archives.length,2);
  const pending=h.state.mediaDecisions.get(h.eventId);pending.direction={...pending.direction,status:'selected',mediaIds:[h.mediaId]};pending.agreement={status:'pending',mediaIds:[],divergent:false};h.rerender();
  assert.equal(button('[data-gate="media"]').getAttribute('aria-pressed'),'false','Un choix DG seul n’est pas un accord final.');
  h.state.workflows.set(h.eventId,{stage:'media_in_progress'});h.rerender();
  if(role==='admin')assert(button('[data-workflow-stage="media_review"]'),'Le visuel en préparation peut être présenté à nouveau.');
  h.state.workflows.set(h.eventId,{stage:'content_review'});h.rerender();
  assert(button('[data-media-validation-force-open]').disabled,'Forcer le visuel ne signe pas implicitement le texte.');
  workspace.destroy();
  console.log(`✓ V2 ${role} : clic Visuel, motif, forçage, retrait, états cohérents, sans dialogue natif.`);
}
