import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {initializeTestEnvironment} from '@firebase/rules-unit-testing';
import * as sdk from 'firebase/firestore';
import {mediaSelectionBlocked} from './media-choice-ui.js';

const source = await fs.readFile(new URL('./firebase-client.js', import.meta.url), 'utf8');
const [host, port] = (process.env.FIRESTORE_EMULATOR_HOST || '127.0.0.1:8187').split(':');
const environment = await initializeTestEnvironment({projectId:'cockpit-media-decision-test', firestore:{host,port:Number(port),rules:await fs.readFile(new URL('./firestore.rules',import.meta.url),'utf8')}});
const profile = role => ({uid:`client-${role}`,role,displayLabel:role==='admin'?'Communications test':'Direction test'});
const client = role => {
  const context = {...sdk,db:environment.authenticatedContext(profile(role).uid).firestore(),crypto:globalThis.crypto,mediaSelectionBlocked,requireWritable:()=>{},recordConfirmedWrites:()=>{}};
  const part=(from,to)=>source.slice(source.indexOf(from),source.indexOf(to,source.indexOf(from))).replaceAll('export async function','async function').replaceAll('export function','function');
  const code=part('function changeArchiveEntry(', '\nexport ') + '\n' + part('const workflowStages =', '\nexport function subscribeWorkflowStates') + '\n' + part('const MAX_MEDIA_CHOICES', '\nexport function subscribeMediaDecisions');
  return {...context,...new Function(...Object.keys(context),code+'\nreturn {setMediaDecision,setWorkflowStage,setCommunicationsTextApproval,setCompletionOverride};')(...Object.values(context))};
};
const admin=client('admin'),director=client('director');
let count=0;
const seed=async stage=>environment.withSecurityRulesDisabled(async ctx=>{
  const db=ctx.firestore();
  for(const role of ['admin','director']) await sdk.setDoc(sdk.doc(db,'users',profile(role).uid),{role,active:true,displayLabel:profile(role).displayLabel});
  await sdk.setDoc(sdk.doc(db,'workflowStates','client-sept10'),{eventId:'client-sept10',stage,updatedAt:sdk.Timestamp.now(),updatedBy:profile('admin').uid,updatedByLabel:profile('admin').displayLabel});
  for(const id of ['photo-current','photo-other']) await sdk.setDoc(sdk.doc(db,'mediaLinks',id),{eventId:'client-sept10',archived:false,publicationBlocked:true,rightsStatus:'Droits à confirmer'});
  await sdk.deleteDoc(sdk.doc(db,'mediaDecisions','client-sept10'));
});
const decision=async()=> (await sdk.getDoc(sdk.doc(admin.db,'mediaDecisions','client-sept10'))).data();
const stage=async()=> (await sdk.getDoc(sdk.doc(admin.db,'workflowStates','client-sept10'))).data().stage;
try {
  await seed('content_review');
  await admin.setCommunicationsTextApproval('client-sept10','Version relue FR / EN',true,profile('admin'));
  const workflowRef=sdk.doc(admin.db,'workflowStates','client-sept10');
  const ownBefore=(await sdk.getDoc(workflowRef)).data().communicationsTextApproval;
  await assert.rejects(()=>admin.setCompletionOverride('client-sept10',true,' ',profile('admin')));count++;
  await admin.setCompletionOverride('client-sept10',true,'Clôture décidée par Valentin',profile('admin'));count++;
  const closed=(await sdk.getDoc(workflowRef)).data();
  assert.equal(closed.stage,'content_review','La clôture ne signe pas le texte de la direction.');
  assert.equal(closed.completionOverride.active,true);
  assert.deepEqual(closed.communicationsTextApproval,ownBefore);
  assert.equal(await decision(),undefined,'Aucun avis visuel n’est créé pour forcer la clôture.');
  const archives=await sdk.getDocs(sdk.query(sdk.collection(admin.db,'changeArchive'),sdk.limit(100)));
  assert(archives.docs.some(d=>d.data().after.completionOverride?.reason==='Clôture décidée par Valentin'));
  await assert.rejects(()=>director.setCompletionOverride('client-sept10',true,'Autre',profile('director')));count++;
  const dgRef=sdk.doc(director.db,'workflowStates','client-sept10');
  await assert.rejects(()=>sdk.updateDoc(dgRef,{completionOverride:{...closed.completionOverride,actorUid:profile('director').uid},updatedBy:profile('director').uid}));count++;
  await assert.rejects(()=>sdk.updateDoc(dgRef,{completionOverride:sdk.deleteField(),updatedBy:profile('director').uid}));count++;
  await director.setWorkflowStage('client-sept10','content_approved',profile('director'));count++;
  assert.deepEqual((await sdk.getDoc(workflowRef)).data().completionOverride,closed.completionOverride,'La confirmation personnelle d’Annie conserve la clôture.');
  await admin.setCompletionOverride('client-sept10',false,'Rouvrir le travail',profile('admin'));count++;
  assert.equal((await sdk.getDoc(workflowRef)).data().completionOverride.active,false);
  assert.equal(await stage(),'content_approved','Rouvrir conserve aussi les nouveaux avis, sans retour arbitraire.');
  await seed('proposal');
  await admin.setCompletionOverride('client-sept10',true,'Sans validations',profile('admin'));count++;
  assert.equal(await stage(),'proposal');
  for(const role of ['admin','director']) {
    await seed('media_review');
    await admin.setMediaDecision('client-sept10','photo-current',true,profile('admin')); count++;
    const actor=role==='admin'?admin:director;
    await actor.setMediaDecision('client-sept10','photo-current',true,profile(role),{override:true,reason:'Validation explicite du visuel'}); count++;
    assert.equal(await stage(),'final_approved');
    assert.equal((await decision()).override.actorUid,profile(role).uid);
    assert.equal((await decision()).direction.status,role==='admin'?'none':'selected');
    await actor.setMediaDecision('client-sept10','photo-current',false,profile(role)); count++;
    assert.equal(await stage(),'media_review');
    assert.equal((await decision()).override.active,false);
  }
  await seed('media_review');
  await admin.setMediaDecision('client-sept10','photo-current',true,profile('admin'));
  await director.setMediaDecision('client-sept10','photo-current',true,profile('director')); count++;
  assert.equal(await stage(),'final_approved');
  assert.equal((await decision()).agreement.status,'agreed');
  await director.setMediaDecision('client-sept10','photo-other',true,profile('director')); count++;
  assert.equal(await stage(),'final_approved');
  assert.equal((await decision()).agreement.status,'direction_approved');
  assert.deepEqual((await decision()).communications.mediaIds,['photo-current'],'Le choix de Valentin reste distinct.');
  await seed('content_review');
  await director.setMediaDecision('client-sept10','photo-current',true,profile('director'));count++;
  assert.equal(await stage(),'content_review');
  assert.equal((await decision()).agreement.status,'direction_approved');
  await director.setWorkflowStage('client-sept10','content_approved',profile('director'));count++;
  assert.equal(await stage(),'final_approved');
  await director.setWorkflowStage('client-sept10','content_review',profile('director'));count++;
  assert.equal(await stage(),'content_review');
  assert.equal((await decision()).agreement.status,'direction_approved');
  await admin.setCommunicationsTextApproval('client-sept10','Texte FR / EN',true,profile('admin'));count++;
  assert.equal(await stage(),'content_review','Préapprouver pour Valentin ne signe pas Annie.');
  await assert.rejects(()=>director.setCommunicationsTextApproval('client-sept10','Texte FR / EN',true,profile('director')));
  const ownApproval=(await sdk.getDoc(sdk.doc(admin.db,'workflowStates','client-sept10'))).data().communicationsTextApproval;
  await assert.rejects(()=>sdk.updateDoc(sdk.doc(director.db,'workflowStates','client-sept10'),{communicationsTextApproval:{...ownApproval,actorUid:profile('director').uid},updatedBy:profile('director').uid}));
  await assert.rejects(()=>sdk.updateDoc(sdk.doc(director.db,'workflowStates','client-sept10'),{communicationsTextApproval:sdk.deleteField(),updatedBy:profile('director').uid}));
  await director.setWorkflowStage('client-sept10','content_approved',profile('director'));count++;
  assert.deepEqual((await sdk.getDoc(sdk.doc(admin.db,'workflowStates','client-sept10'))).data().communicationsTextApproval,ownApproval);
  await assert.rejects(()=>director.setWorkflowStage('client-sept10','published',profile('director')));
  await admin.setWorkflowStage('client-sept10','published',profile('admin'));count++;
  assert.equal(await stage(),'published');
  await seed('content_approved');
  await director.setMediaDecision('client-sept10','photo-current',true,profile('director'),{multiple:true});count++;
  assert.equal(await stage(),'content_approved','Une seule carte ne termine pas un carrousel.');
  await director.setMediaDecision('client-sept10','photo-other',true,profile('director'),{multiple:true});count++;
  assert.equal(await stage(),'final_approved');
  await director.setMediaDecision('client-sept10','photo-current',false,profile('director'),{multiple:true});count++;
  assert.equal(await stage(),'media_review');
  // Production 30 septembre : décision créée par l'import sans schemaVersion.
  // Confirmer le texte écrit aussi la décision visuelle, même sans choix DG.
  for (const role of ['director','admin']) {
    await seed('content_review');
    await admin.setMediaDecision('client-sept10','photo-current',true,profile('admin'));
    await admin.setCommunicationsTextApproval('client-sept10','Texte de référence',true,profile('admin'));
    await environment.withSecurityRulesDisabled(async ctx=>sdk.updateDoc(sdk.doc(ctx.firestore(),'mediaDecisions','client-sept10'),{schemaVersion:sdk.deleteField()}));
    const actor=role==='director'?director:admin;
    const oppositeBefore=(await decision())[role==='director'?'communications':'direction'];
    await actor.setWorkflowStage('client-sept10','content_approved',profile(role));count++;
    assert.equal((await decision()).schemaVersion,2);
    assert.deepEqual((await decision())[role==='director'?'communications':'direction'],oppositeBefore);
    await actor.setMediaDecision('client-sept10','photo-current',true,profile(role));count++;
    assert.deepEqual((await decision())[role==='director'?'communications':'direction'],oppositeBefore);
    await assert.rejects(()=>sdk.updateDoc(sdk.doc(actor.db,'mediaDecisions','client-sept10'),{schemaVersion:3,updatedBy:profile(role).uid}));
    if(role==='director') await assert.rejects(()=>actor.setWorkflowStage('client-sept10','published',profile(role)));
  }
  console.log(`✓ ${count} transactions du client réel avec les règles, deux rôles, forçage et retour arrière.`);
} finally { await environment.cleanup(); }
