import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {parseHTML} from 'linkedom';
import {fixtureHTML,mockAPI} from './workspace-test-fixture.mjs';
import {mountWorkspace} from './workspace-v2.js';
import {installMediaValidationFixture} from './media-validation-test-fixture.mjs';
import {buildTaskProgressPresentation} from './task-progress-ui.js';
const source=await fs.readFile(new URL('./cockpit-ui.js',import.meta.url),'utf8');
const clientSource=await fs.readFile(new URL('./firebase-client.js',import.meta.url),'utf8');
const settle=()=>new Promise(resolve=>setTimeout(resolve,0));
assert.equal(buildTaskProgressPresentation({stage:'media_review'},{direction:{status:'selected',mediaIds:['photo']},agreement:{status:'pending'}}).media,false,'Le suivi des tâches ne confond pas choix DG et validation finale.');
for (const stage of ['media_in_progress','media_changes_requested']) assert.equal(buildTaskProgressPresentation({stage}).text,true,'Une correction média conserve le feu texte.');
for(const role of ['admin','director']) {
  const {document,window}=parseHTML(`<html><body>${fixtureHTML}</body></html>`);
  window.location={hash:'#/publications/test-first',search:'?interface=v2',href:'http://localhost/?interface=v2#/publications/test-first'};
  window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
  window.requestAnimationFrame=fn=>setTimeout(fn,0);window.cancelAnimationFrame=clearTimeout;
  globalThis.MutationObserver=window.MutationObserver;
  globalThis.CustomEvent=window.CustomEvent;
  globalThis.document=document;globalThis.window=window;
  const h=installMediaValidationFixture({document,window,source,clientSource,role,taskError:true});
  const api=mockAPI(document,window,role);api.getWorkflow=id=>h.state.workflows.get(id);api.getMedia=()=>[...h.state.mediaByEvent.values()].flat();api.getMediaDecision=id=>h.state.mediaDecisions.get(id);
  const workspace=mountWorkspace(api);
  const button=selector=>h.card.querySelector(selector);
  assert.equal(button('[data-gate="media"]').disabled,false,'Le feu visuel est actionnable en V2.');
  const panel=button('[data-media-validation-panel]');panel.open=false;
  if(role==='admin')assert.match(button('[data-media-validation-help]').textContent,/Votre choix est enregistré.*pas besoin de forcer/,'Un choix déjà enregistré ne pousse pas à forcer une validation.');
  button('[data-gate="media"]').click();assert.equal(panel.open,true);
  assert.equal(button('[data-gate="publication"]').disabled,true);
  if(role==='director') {
    assert(button('[data-media-validation-force-open]').hidden,'Annie ne doit pas avoir à forcer.');
    h.state.workflows.set(h.eventId,{eventId:h.eventId,stage:'content_review'});
    h.state.mediaDecisions.get(h.eventId).communications.mediaIds=['test-photo-second'];h.rerender();
    button('[data-media-validation-panel] [data-media-decision]').click();await settle();
    assert.equal(h.state.mediaDecisions.get(h.eventId).agreement.status,'direction_approved');
    assert.equal(h.state.workflows.get(h.eventId).stage,'content_review','Le visuel ne signe pas le texte.');
    assert.equal(button('[data-gate="media"]').getAttribute('aria-pressed'),'true');
    button('[data-gate="content"]').click();await settle();
    assert.equal(h.state.workflows.get(h.eventId).stage,'final_approved');
    assert.equal(h.events.at(-1).message,'Étape de validation enregistrée.','Le retour ne doit pas être inversé par le rafraîchissement du bouton.');
    assert(button('[data-gate="publication"]').disabled,'Terminé reste réservé à Valentin.');
    button('[data-gate="content"]').click();await settle();
    assert.equal(h.state.workflows.get(h.eventId).stage,'content_review');
    assert.equal(button('[data-gate="media"]').getAttribute('aria-pressed'),'true','Réviser le texte conserve l’avis visuel.');
    button('[data-media-validation-panel] [data-media-decision]').click();await settle();
    assert.equal(button('[data-gate="media"]').getAttribute('aria-pressed'),'false');
    assert.equal(h.events.filter(e=>e.error).length,0,'Un suivi secondaire indisponible ne signale pas un échec d’approbation.');
    workspace.destroy();console.log('✓ V2 direction : image avant texte, choix différent, approbation, retrait et Terminé réservé.');
    continue;
  }
  button('[data-media-validation-force-open]').click();
  assert(!button('[data-media-validation-force]').hasAttribute('hidden'));
  button('[data-media-override]').click();await settle();assert.equal(h.writes.length,0,'Un motif vide ne déclenche aucune écriture.');
  button('[data-media-override-reason]').value='Aval confirmé pour cette photographie';
  h.rerender();assert.equal(button('[data-media-override-reason]').value,'Aval confirmé pour cette photographie');
  button('[data-media-validation-panel] [data-media-override]').click();await settle();
  assert.equal(h.state.workflows.get(h.eventId).stage,'final_approved',JSON.stringify(h.events));
  assert.equal(h.state.mediaDecisions.get(h.eventId).override.actorRole,role);
  assert.match(button('[data-media-validation-help]').textContent,/validation forcée est enregistrée/,'Le retour confirme la décision forcée sans suggérer un accord des deux rôles.');
  if(role==='admin')assert.equal(h.state.mediaDecisions.get(h.eventId).direction.status,'none');
  assert.equal(h.archives.length,1);
  button('[data-media-validation-panel] [data-media-decision]').click();await settle();
  assert.equal(h.state.workflows.get(h.eventId).stage,'media_review');
  assert.equal(h.state.mediaDecisions.get(h.eventId).override.active,false);
  assert.equal(button('[data-gate="publication"]').disabled,true);
  assert.equal(h.archives.length,2);
  const pending=h.state.mediaDecisions.get(h.eventId);pending.direction={...pending.direction,status:'selected',mediaIds:[h.mediaId]};pending.agreement={status:'pending',mediaIds:[],divergent:false};h.rerender();
  assert.equal(button('[data-gate="media"]').getAttribute('aria-pressed'),'false','Le feu personnel ne signe pas l’autre rôle.');
  h.state.workflows.set(h.eventId,{stage:'media_in_progress'});h.rerender();
  if(role==='admin')assert(button('[data-workflow-stage="media_review"]'),'Le visuel en préparation peut être présenté à nouveau.');
  h.state.workflows.set(h.eventId,{stage:'content_review'});h.rerender();
  assert(button('[data-media-validation-force-open]').disabled,'Forcer le visuel ne signe pas implicitement le texte.');
  button('[data-gate="content"]').click();await settle();
  assert.equal(h.state.workflows.get(h.eventId).stage,'content_review','L’avis de Valentin ne signe pas Annie.');
  assert.equal(button('[data-gate="content"]').getAttribute('aria-pressed'),'true');
  h.plan.copy='Nouvelle version à vérifier';h.rerender();
  assert.equal(button('[data-gate="content"]').getAttribute('aria-pressed'),'false','Une modification invalide l’approbation de la version précédente.');
  button('[data-gate="content"]').click();await settle();
  await new Promise(resolve=>setTimeout(resolve,3));
  h.state.commentsByEvent.set(h.eventId,[{id:'annie-review',authorUid:'test-director',createdAt:Date.now(),comment:'À corriger',resolved:false}]);h.rerender();
  assert.equal(button('[data-gate="content"]').getAttribute('aria-pressed'),'false','Un commentaire remet la préapprobation en vérification.');
  await new Promise(resolve=>setTimeout(resolve,3));
  button('[data-gate="content"]').click();await settle();
  assert.equal(button('[data-gate="content"]').getAttribute('aria-pressed'),'true','La version relue peut être réapprouvée.');
  workspace.destroy();
  console.log(`✓ V2 ${role} : clic Visuel, motif, forçage, retrait, états cohérents, sans dialogue natif.`);
}
