import assert from "node:assert/strict";
import fs from "node:fs/promises";
import { parseHTML } from "linkedom";
import { monthDays, validCivilDate, sortPublications, parseRoute, routeHash, filterPublications, todayKey, publicationState, safeLink } from "./workspace-model.mjs";
import { fixtures, fixtureHTML, mockAPI } from "./workspace-test-fixture.mjs";
import { mountWorkspace } from "./workspace-v2.js";
let checks = 0;
function check(label, run) { run(); checks++; console.log("✓ " + label); }
check("dates civiles et années bissextiles", () => { assert(validCivilDate("2028-02-29")); assert(!validCivilDate("2026-02-29")); assert(!validCivilDate("2026-13-01")); });
check("calendrier de 42 jours, du lundi au dimanche", () => { for (const month of ["2026-09","2026-12","2027-01","2028-02"]) { const days = monthDays(month); assert.equal(days.length,42); assert.equal(new Date(days[0]+"T12:00Z").getUTCDay(),1); assert.equal(new Set(days).size,42); } });
check("tri sans mutation et dates invalides en fin", () => { const input = [{id:"z",dateIso:"2026-09-13"},{id:"b",dateIso:"2026-09-01"},{id:"a",dateIso:"2026-09-01"},{id:"invalid",dateIso:"bad"}]; const before=JSON.stringify(input); assert.deepEqual(sortPublications(input).map(p=>p.id),["a","b","z","invalid"]); assert.equal(JSON.stringify(input),before); });
check("jour civil de Toronto près de minuit UTC", () => assert.equal(todayKey(new Date("2026-09-08T01:00Z")),"2026-09-07"));
check("routes stables et anciennes ancres", () => { assert.equal(parseRoute(routeHash("publications","id / é")).id,"id / é"); assert.equal(parseRoute("#sources").legacy,"sources"); assert.doesNotThrow(()=>parseRoute("#/publications/%oops")); });
check("calendrier conserve le passé sans archives éditoriales", () => { const ids=filterPublications(fixtures,{view:"calendrier",today:"2026-09-07"}).map(p=>p.id); assert(ids.includes("test-past")); assert(!ids.includes("test-archived")); assert(!ids.includes("test-reserve")); });
check("archives et réserve demeurent accessibles", () => { assert(filterPublications(fixtures,{view:"reserve"}).some(p=>p.id==="test-reserve")); assert(filterPublications(fixtures,{view:"archives"}).some(p=>p.id==="test-archived")); });
check("pas de fausse approbation et liens externes sûrs", () => { assert.equal(publicationState({contentApproved:true,mediaApproved:false}).tone,"waiting"); assert.equal(safeLink("javascript:alert(1)"),""); });
const {document,window} = parseHTML("<!doctype html><html><head></head><body>"+fixtureHTML+"</body></html>");
globalThis.document=document; globalThis.window=window; globalThis.MutationObserver=window.MutationObserver; globalThis.CustomEvent=window.CustomEvent;
Object.defineProperty(window.HTMLSelectElement.prototype,"value",{configurable:true,get(){return this.getAttribute("data-test-value")||""},set(v){this.setAttribute("data-test-value",v)}});
const url = new URL("http://localhost:8766/workspace-fixture.html?interface=v2#/accueil");
window.location=url; window.history={pushState(_s,_t,hash){url.hash=hash}}; window.scrollTo=()=>{}; window.scrollY=0;
const api=mockAPI(document,window); const sourceJSON=JSON.stringify(fixtures);
const controls=[...document.querySelectorAll("button,input,textarea,a,details")];
let clicked=0; const originalChoose=document.querySelector('[data-choose="one"]'); originalChoose.addEventListener("click",()=>clicked++);
const workspace=mountWorkspace(api);
check("montage opt-in et quatre espaces",()=>{assert.equal(document.documentElement.dataset.workspace,"v2");assert.equal(document.querySelectorAll("[data-v2-space]").length,4);});
workspace.navigate("#/publications/test-first");
check("les contrôles sont déplacés, jamais copiés ni perdus",()=>{assert(controls.every(n=>n.isConnected));assert.equal(document.querySelector('[data-choose="one"]'),originalChoose);originalChoose.click();assert.equal(clicked,1);});
check("galerie complète et une seule proposition visible",()=>{const card=document.querySelector('[data-item-id="test-first"]');assert.equal(card.querySelectorAll("[data-v2-thumbnail]").length,4);assert.equal(card.querySelectorAll("[data-v2-slide-hidden]").length,3);card.querySelector('[data-v2-thumbnail="2"]').click();assert(!card.querySelector('[data-media-id="three"]').hasAttribute("data-v2-slide-hidden"));assert.equal(clicked,1);});
check("saisie et informations détaillées conservées après navigation",()=>{const input=document.querySelector('[data-item-id="test-first"] [data-comment]');input.value="Brouillon non envoyé";workspace.navigate("#/projets");workspace.navigate("#/publications/test-first");assert.equal(input.value,"Brouillon non envoyé");assert(input.isConnected);assert(document.querySelector(".v2-more [data-decision]"));});
document.querySelector('[data-item-id="test-first"] [data-v2-history]').click();
await new Promise(resolve=>setTimeout(resolve,5));
check("historique avant/après en lecture seule",()=>{const content=document.querySelector(".v2-text-history").textContent;assert(content.includes("Ancienne formulation"));assert(content.includes("Nouvelle formulation"));assert(content.includes("dossier source"));assert.equal(JSON.stringify(fixtures),sourceJSON);});
workspace.navigate("#/publications?vue=calendrier");
check("calendrier social distinct et agenda mobile",()=>{assert.equal(document.querySelectorAll(".v2-day").length,42);assert(document.querySelector(".v2-mobile-agenda"));assert(document.querySelector(".project-calendar-shell").closest("[data-v2-concealed]"));});
workspace.navigate("#/projets?vue=calendrier");
check("calendrier projet original conservé",()=>{assert(document.querySelector(".project-calendar-shell").hasAttribute("data-v2-target"));assert.equal(document.querySelectorAll(".v2-day").length,0);});
workspace.navigate("#/projets?vue=archives");
check("projets archivés consultables sans réactivation",()=>{assert(document.querySelector('a[href="#/projets/test-archive"]'));workspace.navigate("#/projets/test-archive");assert(document.querySelector(".internal-project.is-archived[data-v2-target]"));});
workspace.navigate("#/bibliotheque");
check("bibliothèque garde les liens des originaux",()=>assert(document.querySelector('a[href="https://example.org/archive.pdf"]')));
workspace.destroy();
check("démontage restaure les nœuds et l’interface classique",()=>{assert(controls.every(n=>n.isConnected));assert(!document.documentElement.dataset.workspace);assert(!document.querySelector("#workspace-v2"));assert(document.querySelector('.post>.cockpit-controls>[data-workflow], .post>.cockpit-controls>.cockpit-workflow'));assert.equal(document.querySelector('[data-choose="one"]'),originalChoose);});
const ui=await fs.readFile(new URL("./cockpit-ui.js",import.meta.url),"utf8");
const v2=await fs.readFile(new URL("./workspace-v2.js",import.meta.url),"utf8");
check("aucun writer Firebase parallèle et activation explicite",()=>{assert(!/setDoc|updateDoc|writeBatch|savePublicationContent|deleteDoc/.test(v2));assert(ui.includes('get("interface") === "v2"'));});
console.log(`✓ ${checks} contrôles V2 : calendrier, galerie, droits d’interface, versions et conservation.`);
