import assert from 'node:assert/strict';
import {parseHTML} from 'linkedom';
import {normalizePublicationDraft,schedulePayloadFromDraft,publicationFromScheduleRow,validatePublicationDraft} from './publication-editor-schema.mjs';
import {mountWorkspace} from './workspace-v2.js';
import {fixtureHTML,mockAPI} from './workspace-test-fixture.mjs';
const copy='FR — '+ 'Un lac, une communauté. '.repeat(60)+'\n=========================================\nEN — '+'One lake, one community. '.repeat(60);
const draft=normalizePublicationDraft({title:'Retour AGA',dateIso:'2026-10-03',copy,templateId:'newsletter'});
assert.equal(validatePublicationDraft(draft).length,0);
const patch=schedulePayloadFromDraft(draft,{});
assert.equal(publicationFromScheduleRow(patch).templateId,'newsletter');
const {document,window}=parseHTML(`<html><body>${fixtureHTML}</body></html>`);
window.location={hash:'#/publications/test-first',href:'http://localhost/?interface=v2#/publications/test-first'};
window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
globalThis.MutationObserver=window.MutationObserver;
globalThis.CustomEvent=window.CustomEvent;
const api=mockAPI(document,window);const posts=api.getPosts().map(p=>p.id==='test-first'?{...p,copy,templateId:'newsletter'}:p);api.getPosts=()=>posts;
const workspace=mountWorkspace(api);
assert.match(document.querySelector('.v2-copy-count').textContent,/infolettre bilingue/);
assert.equal(document.querySelector('.v2-copy-count').dataset.warning,undefined,'Newsletter does not inherit social character warning.');
assert.match(document.querySelector('.v2-copy-count').textContent,/aucun envoi automatique/);
workspace.destroy?.();
console.log('✓ Infolettre: type retained, long bilingual copy, no false social limit or send claim.');
