import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';
import * as mediaUI from './media-choice-ui.js';

const ui=fs.readFileSync(new URL('./cockpit-ui.js',import.meta.url),'utf8');
const client=fs.readFileSync(new URL('./firebase-client.js',import.meta.url),'utf8');
const {document}=parseHTML('<html><body><article class="post" data-item-id="test-post"><div data-media-count></div><div data-media-nav></div><div data-media-gallery></div></article></body></html>');
const row={id:'media-photo',eventId:'test-post',kind:'image',url:'https://example.org/photo.jpg',label:'Photo de terrain',publicationBlocked:true,rightsStatus:'droits à confirmer',archived:false};
const state={profile:{uid:'annie',role:'director'},mediaByEvent:new Map([['test-post',[row]]]),commentsByEvent:new Map(),mediaDecisions:new Map(),workflows:new Map([['test-post',{stage:'content_approved'}]]),mediaContextLoading:new Set()};
const context={...mediaUI,document,state,getPlanItem:()=>({}),safeMediaUrl:v=>v,mediaPreviewUrl:()=>'',stateTimestampMillis:()=>0,workflowTextApprovedStages:new Set(['content_approved']),esc:v=>String(v),mediaKindIcons:{image:'Image'},mediaStageLabels:{},canEdit:()=>true,setupMediaNavigation:()=>{},queueMicrotask};
vm.createContext(context);
vm.runInContext(ui.slice(ui.indexOf('function renderMediaForCard('),ui.indexOf('\nfunction setupMediaNavigation(')),context);
const card=document.querySelector('.post');
context.renderMediaForCard(card);
assert.equal(card.querySelectorAll('[data-media-decision]:not([disabled])').length,2,'Les droits incertains laissent les deux accès de sélection disponibles.');
assert(card.querySelector('.cockpit-media-rights-note').textContent.includes('Droits à vérifier'));
assert(!card.querySelector('[data-save-media-comment]').closest('details'),'Le commentaire reste accessible hors des informations repliées.');
assert(!card.querySelector('[data-media-override]').closest('details'),'La décision finale est directement accessible.');
let input=card.querySelector('[data-media-comment]');input.value='La photo convient; quel crédit utiliser ?';input.dataset.dictated='true';
context.renderMediaForCard(card);
input=card.querySelector('[data-media-comment]');assert.equal(input.value,'La photo convient; quel crédit utiliser ?');assert.equal(input.dataset.dictated,'true');
card.querySelector('[data-save-media-comment]').disabled=true;
context.renderMediaForCard(card);assert(card.querySelector('[data-save-media-comment]').disabled,'Le rafraîchissement ne permet pas un deuxième envoi concurrent.');
state.profile.role='admin';context.renderMediaForCard(card);assert(card.querySelector('[data-media-decision]:not([disabled])'));
state.workflows.set('test-post',{stage:'content_review'});context.renderMediaForCard(card);assert(!card.querySelector('[data-media-override]'),'La décision finale média ne signe pas le texte.');
assert(card.querySelector('[data-media-decision]:not([disabled])'),'Le choix simple précède librement le texte.');
const originalRights=row.rightsStatus;row.rightsStatus='référence anatomiquement incorrecte';context.renderMediaForCard(card);assert(!card.querySelector('[data-media-decision]:not([disabled])'));row.rightsStatus=originalRights;
row.archived=true;context.renderMediaForCard(card);assert(!card.querySelector('[data-media-decision]'),'Une archive reste préservée hors des propositions actives.');

const selected=(role,ids)=>({status:ids.length?'selected':'revoked',mediaIds:ids,actorUid:role,actorRole:role,actorLabel:role,decidedAt:1});
const empty=()=>({active:false,mediaIds:[],reason:'',actorUid:'',actorLabel:'',actorRole:'',decidedAt:null});
let decision={communications:selected('admin',['media-photo']),direction:selected('director',[]),override:empty(),agreement:{status:'pending',mediaIds:[],divergent:false}};
let workflow={eventId:'test-post',stage:'content_review'};row.archived=false;
const writes=[];
const c={mediaSelectionBlocked:mediaUI.mediaSelectionBlocked,db:{},requireWritable:()=>{},doc:(_db,collection,id)=>`${collection}/${id}`,crypto:{randomUUID:()=> 'local-test'},serverTimestamp:()=>2,contentApprovedWorkflowStages:new Set(['content_approved','media_review','final_approved']),normalizeMediaDecision:v=>v,emptyOverride:empty,mediaDecisionArchiveView:v=>v,recordConfirmedWrites:()=>{},runTransaction:async(_db,fn)=>fn({get:async ref=>({exists:()=>true,data:()=>ref.startsWith('mediaLinks/')?row:ref.startsWith('workflowStates/')?workflow:decision}),set:(ref,data)=>writes.push({ref,data}),update:(ref,data)=>writes.push({ref,data})})};
vm.createContext(c);
const pure=client.slice(client.indexOf('const MAX_MEDIA_CHOICES'),client.indexOf('\nfunction normalizeMediaDecision'));
vm.runInContext(pure.replaceAll('export function','function'),c);
const start=client.indexOf('export async function setMediaDecision('),end=client.indexOf('\nexport function subscribeMediaDecisions',start);
vm.runInContext(client.slice(start,end).replaceAll('export async function','async function'),c);
await c.setMediaDecision('test-post','media-photo',true,{uid:'director',role:'director',displayLabel:'Annie'});
assert.equal(writes.find(w=>w.ref.startsWith('mediaDecisions/')).data.direction.mediaIds[0],'media-photo');
assert(!writes.some(w=>w.data.stage==='final_approved'));
writes.length=0;
await assert.rejects(()=>c.setMediaDecision('test-post','media-photo',true,{uid:'admin',role:'admin',displayLabel:'Valentin'},{override:true,reason:'Mon choix'}),/Validez le texte/);
assert.equal(writes.length,0);
workflow.stage='final_approved';decision.override={...empty(),active:true,actorUid:'admin',actorRole:'admin',mediaIds:['media-photo'],reason:'Mon choix'};decision.agreement={status:'overridden',mediaIds:['media-photo'],divergent:false};
await c.setMediaDecision('test-post','media-photo',false,{uid:'admin',role:'admin',displayLabel:'Valentin'});
assert.equal(writes.find(w=>w.ref.startsWith('mediaDecisions/')).data.override.active,false);
assert.equal(writes.find(w=>w.ref.startsWith('workflowStates/')).data.stage,'media_review');
writes.length=0;row.rightsConfirmed=true;row.publicationBlocked=false;
await c.setMediaRightsConfirmation('media-photo',false,{uid:'admin',role:'admin',displayLabel:'Valentin'});
assert.equal(writes.find(w=>w.ref.startsWith('mediaLinks/')).data.rightsConfirmed,false);
assert.equal(writes.find(w=>w.ref.startsWith('mediaLinks/')).data.publicationBlocked,false);
assert(!writes.some(w=>w.ref.startsWith('mediaDecisions/')),'Les choix sont inchangés lorsque les droits sont remis en attente.');
console.log('✓ Parcours média réel : droits informatifs, accès aux actions, saisie conservée, choix réversible et texte indépendant.');
const feedbackList=document.createElement('div');feedbackList.id='cockpit-feedback-list';document.body.append(feedbackList);
context.feedbackSectionLabels={};
vm.runInContext(ui.slice(ui.indexOf('function renderFeedbackList('),ui.indexOf('\nfunction enhanceFeedbackListEvents(')),context);
context.renderFeedbackList([{id:'open-note',status:'open',message:'À examiner'},{id:'old-note',status:'done',message:'Déjà traité'}]);
assert(feedbackList.querySelector('h3').textContent.includes('1'));
assert(!feedbackList.querySelector('[data-feedback-id="open-note"]').closest('details'));
assert(feedbackList.querySelector('[data-feedback-id="old-note"]').closest('details'));
assert.equal(feedbackList.querySelector('[data-feedback-id="old-note"]').dataset.feedbackStatus,'open');
console.log('✓ Demandes générales : actives en premier, historique replié et remise à traiter explicite.');
