import assert from 'node:assert/strict';
import fs from 'node:fs';
import { parseHTML } from 'linkedom';
import { ANNIE_UID, pendingAnnieRequests, watchAnnieRequests } from './annie-requests.mjs';
import { groupProjects, projectType, projectTheme, projectUrgency } from './project-list-model.mjs';
import { mountWorkspace } from './workspace-v2.js';
import { fixtureHTML, mockAPI } from './workspace-test-fixture.mjs';
const comment=(id,more={})=>({id,authorUid:ANNIE_UID,comment:'Une consigne',sectionId:'test-first',createdAt:new Date('2026-10-03T15:00Z'),...more});
assert.deepEqual(pendingAnnieRequests({comments:[comment('old',{createdAt:new Date('2026-08-01')}),comment('new'),comment('new'),comment('removed',{deleted:true}),comment('resolved',{resolved:true}),comment('other',{authorUid:'other'}),comment('empty',{comment:''})],feedback:[{id:'partial',authorUid:ANNIE_UID,message:'Partiellement fait',status:'in_review',createdAt:new Date('2026-10-04')},{id:'done',authorUid:ANNIE_UID,message:'Fini',status:'done'}]}).map(x=>x.key),['feedback:partial','comment:new','comment:old']);
assert.equal(pendingAnnieRequests({comments:[comment('approved',{read:true,textApproved:true,mediaApproved:true})]}).length,1);
const callbacks={};let stopped=0,snapshot;
const stop=watchAnnieRequests({subscribe:(kind,onNext,onError)=>{callbacks[kind]={onNext,onError};return()=>stopped++;},onUpdate:s=>snapshot=s});
callbacks.comments.onNext([comment('one')],{fromCache:true});callbacks.feedback.onNext([],{fromCache:false});assert(snapshot.sources.comments.fromCache);
callbacks.comments.onNext([comment('two')],{fromCache:false});assert(!snapshot.sources.comments.fromCache);callbacks.feedback.onError();assert(snapshot.sources.feedback.error);assert.equal(snapshot.comments.length,1);
stop();assert.equal(stopped,2);const retained=snapshot;callbacks.comments.onNext([]);assert.equal(snapshot,retained);
const projects=[{id:'carte-fetes-2026',title:'Carte de Noël'},{id:'bilan-sante-lac',title:'Bilan',priority:'high'},{id:'continuite-2027',title:'Continuité',pinned:true},{id:'pilot',title:'Pilote',deadline:'2026-10-06'},{id:'blocked',title:'Projet bloqué',stage:'blocked'},{id:'new',title:'Un nouveau projet'}];
const original=JSON.stringify(projects);assert.equal(projectType(projects[0]),'Communications et outils');assert.equal(projectTheme(projects[1]),'Qualité de l’eau');assert(groupProjects(projects).some(x=>x.label==='Autres projets'));assert.equal(groupProjects(projects,'urgency','2026-10-04')[0].label,'Blocage à résoudre');assert.equal(JSON.stringify(projects),original);
assert.equal(projectUrgency({deadline:'2026-99-20'},'2026-10-04'),'Échéance à préciser');assert.equal(projectUrgency({deadline:'2026-10-01'},'2026-10-04'),'Échéance à réexaminer');assert.equal(projectUrgency({deadline:'2026-10-20'},'2026-10-04'),'Échéance ultérieure');
const {document,window}=parseHTML('<html><head></head><body>'+fixtureHTML+'</body></html>');
Object.assign(globalThis,{document,window,MutationObserver:window.MutationObserver,CustomEvent:window.CustomEvent});
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this.getAttribute('data-value')||''},set(v){this.setAttribute('data-value',v)}});
window.location=new URL('http://localhost/?interface=v2#/projets');window.history={pushState(_a,_b,hash){window.location.hash=hash}};window.scrollTo=()=>{};
let update,subscriptions=0,unsubscriptions=0;const desktop=new window.EventTarget();desktop.matches=true;window.matchMedia=()=>desktop;
const api=mockAPI(document,window);api.watchAnnieRequests=callback=>{subscriptions++;update=callback;return()=>unsubscriptions++};
const view=mountWorkspace(api);assert.equal(subscriptions,1);assert(document.querySelector('.v2-annie-panel'));assert.equal(document.querySelector('[data-v2-project-grouping]').value,'type');assert.match(document.querySelector('.v2-tabs').textContent,/Pistes de financement/);
const ready={comments:{loaded:true,fromCache:false},feedback:{loaded:true,fromCache:false}};
update({comments:[comment('live',{comment:'<img src=x onerror=alert(1)> Corriger le texte'})],feedback:[],sources:ready});
assert.equal(document.querySelector('[data-annie-count]').textContent,'1');assert.equal(document.querySelector('[data-annie-live]').textContent,'En direct');assert(!document.querySelector('.v2-annie-request img'));assert.equal(document.querySelector('.v2-annie-request a').getAttribute('href'),'#/publications/test-first');
document.querySelector('.internal-project').dataset.relatedFeedback='general-project';update({comments:[],feedback:[{id:'general-project',authorUid:ANNIE_UID,message:'La demande générale concerne ce projet',sectionId:'cockpit',status:'in_review'}],sources:ready});assert.equal(document.querySelector('.v2-annie-request a').getAttribute('href'),'#/projets/test-project');
const field=document.querySelector('[data-comment]');field.value='Brouillon humain conservé';update({comments:[],feedback:[],sources:ready});assert.equal(field.value,'Brouillon humain conservé');assert.match(document.querySelector('[data-annie-requests]').textContent,/Aucune demande/);
update({comments:[],feedback:[],sources:{comments:{error:true},feedback:{loaded:true}}});assert.match(document.querySelector('[data-annie-live]').textContent,/vérifier/);assert.doesNotMatch(document.querySelector('[data-annie-requests]').textContent,/Aucune demande/);
desktop.matches=false;desktop.dispatchEvent(new window.Event('change'));assert.equal(unsubscriptions,1);desktop.matches=true;desktop.dispatchEvent(new window.Event('change'));assert.equal(subscriptions,2);view.destroy();assert.equal(unsubscriptions,2);assert(!document.querySelector('.v2-annie-panel'));
const director=mountWorkspace({...api,profile:{uid:'test-director',role:'director'}});assert(!document.querySelector('.v2-annie-panel'));assert.equal(subscriptions,2);director.destroy();
const client=fs.readFileSync(new URL('./firebase-client.js',import.meta.url),'utf8');assert.match(client,/annie-requests:[\s\S]{0,300}includeMetadataChanges: true/);
const indexes=JSON.parse(fs.readFileSync(new URL('./firestore.indexes.json',import.meta.url),'utf8')).indexes;
for(const [group,active]of [['comments','resolved'],['cockpitFeedback','status']])assert(indexes.some(x=>x.collectionGroup===group&&x.fields.map(f=>f.fieldPath).join(',')===`authorUid,${active},createdAt`));
console.log('✓ Demandes anciennes, direct, cache/erreurs, auteur, clôture, saisies, rôles et regroupement des projets.');
